import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navigation from "@/components/Navigation";
import { Providers } from "../app/providers.tsx";

export const metadata: Metadata = {
  title: "MouseMaster.gg",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body className="w-full">
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
          <Navigation />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
